author:
  name: Travelmarx
  email: travelmarx@live.com
  github: travelmarx
highligher: rouge
markdown: kramdown
plugins:
  - jemoji
production_url: https://travelmarx.github.io/scrapbook101/
title: Travelmarx Scrapbook 101
sn: Scrapbook101
