author:
  name: Travelmarx
  email: travelmarx@live.com
  github: travelmarx
highligher: rouge
markdown: kramdown
plugins:
  - jemoji
production_url: https://travelmarx.github.io/scrapbook101/
title: Scrapbook 101
theme: jekyll-theme-minimal 
sn: Scrapbook101
tagline: A simplified PIM System
