author:
  name: Travelmarx
  email: travelmarx@live.com
  github: travelmarx
highligher: rouge
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jemoji
production_url: https://travelmarx.github.io/scrapbook/
title: Travelmarx Scrapbook 101
